CREATE TABLE [dbo].[CinemaPlace]
(
	[Id_CinemaPlace] INT IDENTITY NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(64) NOT NULL,
	[City] NVARCHAR(64) NOT NULL,
	[Street] NVARCHAR(128) NOT NULL,
	[Number] NVARCHAR(8) NOT NULL
)
